---
title: "DATS-6101 Project 1"
author: "Sean Pili"
date: "October 3, 2018"
output: html_document
---

# Plan

##First 

* $\chi^2$ test for each variable to get the relevant ones.
* New variables with combination/permutations for the `InternetService`, `StreamingTv`, `StreamingMovies`

[Source](https://stackoverflow.com/questions/11936339/replace-specific-characters-within-strings) 
```{r data prep}
unique(chrn$StreamingTV)
chrn$StreamingTV <- gsub("No internet service", 0, chrn$StreamingTV)
unique(chrn$StreamingTV)
```

```{r}
for(c in chrn$SeniorCitizen){
  
}
```

```{r}
source('nuisance_reducer.R')
package_apply_all(c('ggplot2','readr'), require)
#import the data 
chrn <- read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
str(chrn)
x1 = as.factor(chrn$Partner)
pap_plot = ggplot(data=chrn,aes(x=Churn))
pap_plot + geom_bar(aes(fill=PaperlessBilling))
# it seems that a most people who churn use paperless billing... interesting.. 
Part_plot = ggplot(data=chrn,aes(x=Churn))
Part_plot + geom_bar(aes(fill=Partner))
# Are singles more likely to churn? looks that way...., or at least... most ppl with partners DIDN'T churn
# might need to just look at percentages here, because there are just MORE PEOPLe WHO didn't churn.... so it's more of a p(churn|factor)
x11()
boxplot(tenure~Churn,data=chrn, main = "Spread of Tenure by customer_status",ylab="#Tenure with company in Months")

 
# let' s do this for the rest of the character varaibles. 
chrn_yes = chrn[chrn$Churn=="Yes",]
chrn_no = chrn[chrn$Churn=="No",]
hist(chrn_yes$tenure)
hist(chrn_no$tenure)
# the means are definitely different here..... 
#let's try 2 histograms??? 
# ANOVA time? logistic regression. 


# the "yes" histogram was what we expected, the no, not quite. 
# it seems people who have been there a while are the ones who end it 
# could it be that they're just dying of old age? lol... check how many are senior citizens... 

churn_rt = 5174/7043

unique(chrn$Churn)

dim(chrn)
5174+1869

```

```{r more plots}
sex_plot = ggplot(data=chrn,aes(x=Churn))
sex_plot + geom_bar(aes(fill=gender))
# gender doesn't seem to play a role 

chrn$SeniorCitizen <- as.factor(chrn$SeniorCitizen)

senior_plot = ggplot(data=chrn,aes(x=Churn))
senior_plot + geom_bar(aes(fill=SeniorCitizen))
#it's not QUITE as extreme... 
# you could, however make the case that it's interesting there are roughly the same number 
# of senior citizens in the group of ppl who churned... v. who didn't, but there were a lot more non senior citizens in the group of ppl who stayed... maybe seniors are more likely to leave 
table(chrn$SeniorCitizen)
# we also just have a bunch more non-senior citizens...


contract_plot = ggplot(data=chrn,aes(x=Churn))
contract_plot + geom_bar(aes(fill=Contract))
table(chrn_yes$Contract)


table(chrn$Contract)[1]/nrow(chrn)
#Overall, 55% of telco's current customers as of last month had month to month contracts
# Making up 42% of the customers who didn't churn.... but a whopping 89% of the customers #who did churn... which appears to make sense. This will be part of our H0

table(chrn_yes$Contract)[1]/nrow(chrn_yes)
# so what we have learned HERE... is that people who have month to month contracts 
# are make up 40% of the people in the 

table(chrn_no$Contract)[1]/nrow(chrn_no)


dependents_plot = ggplot(data=chrn,aes(x=Churn))
dependents_plot + geom_bar(aes(fill=Dependents))

# people with dependents
# the relationship is a bit more pronounced with the people who churned... we COULD look at it 


dependents_plot = ggplot(data=chrn,aes(x=Churn))
dependents_plot + geom_bar(aes(fill=Dependents))




phone_service_plot = ggplot(data=chrn,aes(x=Churn))
phone_service_plot + geom_bar(aes(fill=PhoneService))
# eh, not really worth it. 
table(chrn_yes$PhoneService)[1]/nrow(chrn_yes)
# percentages are hella close, no way.
table(chrn_no$PhoneService)[1]/nrow(chrn_no)



internet_service_plot = ggplot(data=chrn,aes(x=Churn))
internet_service_plot + geom_bar(aes(fill=InternetService))


# well HELLO there internet service..... 
# it appears that customers with fiber optic internet service churned the most..... 
# but it seems to be pretty evenly distributed for the customers who didn't churn... 


online_security_plot = ggplot(data=chrn,aes(x=Churn))
online_security_plot + geom_bar(aes(fill=OnlineSecurity))

# yup, I was right, if they have internet security... they're more likely to churn. 
```

