---
title: "Telco_EDA"
author: "zbuckley"
date: "October 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Helper Functions here for cleanly handling imports
#install_all - function for installing all packages in a list that aren't available
#  inspired by https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#  ex: install_all(c('readr', 'dplyr'))
install_all <- function(list.of.packages) {
  need_install <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
  if(length(need_install)) install.packages(need_install)
}

# package_apply_all - function for calling install_all on list of packages, then applying a function to them
#  inspired by https://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
#  ex: package_apply_all(c('readr', 'dplyr'), require)
package_apply_all <- function(list.of.packages, func) {
  install_all(list.of.packages)
  lapply(list.of.packages, func, character.only = TRUE)
}
```

# Nuisance_Reducer

Using the Nuisance Reducer script we can hide away useful utilities... like loading in a cleaned up data.frame of the telco data.


# Data Exploration

Combining things into yes and no

```{r add_agg}
package_apply_all(c('readr','dplyr'), require)

# TODO: Can this be generalized using ... undefined arguments thingy?
# Inspired by r and dplyr documentation...
count_services <- function(a,b,c,d) {
  val <- 0
  #TODO: had trouble turning this into loop... should take another look
  if (a == "Yes") val <- val + 1
  if (b == "Yes") val <- val + 1
  if (c == "Yes") val <- val + 1
  if (d == "Yes") val <- val + 1
  val
}

# 1) Read in data and convert all character columns to factors
# 2) Mutate some factor columns into Yes/No for later analysis
#    - this changes type back to character
# 3) Mutate all character columns to factors
# 4) add service_count column including number of services available
#
# Implementation Inspired by:
#   https://stackoverflow.com/questions/27668266/dplyr-change-many-data-types
#   https://gist.github.com/ramhiser/93fe37be439c480dc26c4bed8aab03dd#file-character2factor-r-L8 
telco <- read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv') %>%
  mutate_if(sapply(., is.character), as.factor) %>%
  #TODO do we have a reference to this ??? Pedro any idea where you found this?
  mutate(
    StreamingTV = gsub(" internet service", "", StreamingTV), # 'no internet service' should just be No
    StreamingMovies = gsub(" internet service", "", StreamingMovies), # 'no internet service' should just be No
    InternetService = gsub("DSL", "Yes", InternetService), # DSL changed to Yes
    InternetService = gsub("Fiber optic", "Yes", InternetService) # Fiber changed to Yes
  ) %>%
  mutate_if(sapply(., is.character), as.factor) %>% 
  rowwise() %>% mutate(
    #add service_count column containing numbers of services each customer has
    service_count = count_services(StreamingTV, StreamingMovies, InternetService, PhoneService)
  )

str(telco)
```

##Chi-squared stuff

```{r}
package_apply_all(c('vcd'), require)

thing <- chisq.test(telco$Churn,telco[['Contract']])
str(thing)

names <- names(Filter(is.factor, telco))
names

i <- 0
results <- list()
for (n in names) {
  i <- i + 1
  results[[i]] <- list(n, chisq.test(telco$Churn, telco[[n]]))
 # print(n)
  #print(results[[i]])
}

#print(results)


printShit <- function(x) {
  print(results[[x]][[1]])
  print("observed")
  print(results[[x]][[2]]$observed)
  print("expected")
  print(results[[x]][[2]]$expected)
  print("residuals")
  print(results[[x]][[2]]$residuals)
  print("p.value")
  print(results[[x]][[2]]$p.value)
}

#printShit(2)


```

#wtf

Chi-Squared null hypothesis is no relationship between variables

if p-value < .05 reject that and is a relationship between variables




